---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.20.0
  name: sriovnetworknodepolicies.sriovnetwork.openshift.io
spec:
  group: sriovnetwork.openshift.io
  names:
    kind: SriovNetworkNodePolicy
    listKind: SriovNetworkNodePolicyList
    plural: sriovnetworknodepolicies
    singular: sriovnetworknodepolicy
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.matchedNodeCount
      name: Matched
      type: integer
    - jsonPath: .status.readyNodeCount
      name: Ready Nodes
      type: integer
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    - jsonPath: .status.conditions[?(@.type=="Progressing")].status
      name: Progressing
      type: string
    - jsonPath: .status.conditions[?(@.type=="Degraded")].status
      name: Degraded
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: SriovNetworkNodePolicy is the Schema for the sriovnetworknodepolicies
          API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: SriovNetworkNodePolicySpec defines the desired state of SriovNetworkNodePolicy
            properties:
              bridge:
                description: |-
                  contains bridge configuration for matching PFs,
                  valid only for eSwitchMode==switchdev
                properties:
                  ovs:
                    description: contains configuration for the OVS bridge,
                    properties:
                      bridge:
                        description: contains bridge level settings
                        properties:
                          datapathType:
                            description: configure datapath_type field in the Bridge
                              table in OVSDB
                            type: string
                          externalIDs:
                            additionalProperties:
                              type: string
                            description: IDs to inject to external_ids field in the
                              Bridge table in OVSDB
                            type: object
                          failMode:
                            description: configure fail_mode field in the Bridge table
                              in OVSDB (optional). 'secure' or 'standalone'.
                            enum:
                            - secure
                            - standalone
                            type: string
                          otherConfig:
                            additionalProperties:
                              type: string
                            description: additional options to inject to other_config
                              field in the bridge table in OVSDB
                            type: object
                        type: object
                      uplink:
                        description: contains settings for uplink (PF)
                        properties:
                          interface:
                            description: contains settings for PF interface in the
                              OVS bridge
                            properties:
                              externalIDs:
                                additionalProperties:
                                  type: string
                                description: external_ids field in the Interface table
                                  in OVSDB
                                type: object
                              mtuRequest:
                                description: mtu_request field in the Interface table
                                  in OVSDB
                                type: integer
                              options:
                                additionalProperties:
                                  type: string
                                description: options field in the Interface table
                                  in OVSDB
                                type: object
                              otherConfig:
                                additionalProperties:
                                  type: string
                                description: other_config field in the Interface table
                                  in OVSDB
                                type: object
                              type:
                                description: type field in the Interface table in
                                  OVSDB
                                type: string
                            type: object
                        type: object
                    type: object
                type: object
              deviceType:
                default: netdevice
                description: The driver type for configured VFs. Allowed value "netdevice",
                  "vfio-pci". Defaults to netdevice.
                enum:
                - netdevice
                - vfio-pci
                type: string
              eSwitchMode:
                description: NIC Device Mode. Allowed value "legacy","switchdev".
                enum:
                - legacy
                - switchdev
                type: string
              excludeTopology:
                description: Exclude device's NUMA node when advertising this resource
                  by SRIOV network device plugin. Default to false.
                type: boolean
              externallyManaged:
                description: don't create the virtual function only allocated them
                  to the device plugin. Defaults to false.
                type: boolean
              isRdma:
                description: RDMA mode. Defaults to false.
                type: boolean
              linkType:
                description: NIC Link Type. Allowed value "eth", "ETH", "ib", and
                  "IB".
                enum:
                - eth
                - ETH
                - ib
                - IB
                type: string
              mtu:
                description: MTU of VF
                minimum: 1
                type: integer
              needVhostNet:
                description: mount vhost-net device. Defaults to false.
                type: boolean
              nicSelector:
                description: NicSelector selects the NICs to be configured
                properties:
                  deviceID:
                    description: The device hex code of SR-IoV device. Allowed value
                      "0d58", "1572", "158b", "1013", "1015", "1017", "101b".
                    type: string
                  netFilter:
                    description: |-
                      Infrastructure Networking selection filter.
                      Allowed values:
                      - "openstack/NetworkID:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                      - "aws/NetworkID:xxxxxxxx"
                    type: string
                  pfNames:
                    description: Name of SR-IoV PF.
                    items:
                      type: string
                    type: array
                  rootDevices:
                    description: PCI address of SR-IoV PF.
                    items:
                      type: string
                    type: array
                  vendor:
                    description: The vendor hex code of SR-IoV device. Allowed value
                      "8086", "15b3".
                    type: string
                type: object
              nodeSelector:
                additionalProperties:
                  type: string
                description: NodeSelector selects the nodes to be configured
                type: object
              numVfs:
                description: Number of VFs for each PF
                minimum: 0
                type: integer
              priority:
                description: Priority of the policy, higher priority policies can
                  override lower ones.
                maximum: 99
                minimum: 0
                type: integer
              resourceName:
                description: SRIOV Network device plugin endpoint resource name
                type: string
              vdpaType:
                description: VDPA device type. Allowed value "virtio", "vhost"
                enum:
                - virtio
                - vhost
                type: string
            required:
            - nicSelector
            - nodeSelector
            - numVfs
            - resourceName
            type: object
          status:
            description: SriovNetworkNodePolicyStatus defines the observed state of
              SriovNetworkNodePolicy
            properties:
              conditions:
                description: Conditions represent the latest available observations
                  of the SriovNetworkNodePolicy's state
                items:
                  description: Condition contains details for one aspect of the current
                    state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
              matchedNodeCount:
                description: MatchedNodeCount is the number of nodes that match the
                  nodeSelector for this policy
                type: integer
              readyNodeCount:
                description: ReadyNodeCount is the number of matched nodes that have
                  successfully applied the configuration
                type: integer
            required:
            - matchedNodeCount
            - readyNodeCount
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
